# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_class:
#     class: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
production:
  scrape_companies:
    class: CompanyScraperJob
    schedule: "every day at 6am"
    
  scrape_company_cik_and_s1:
    class: CompanyCikScraperJob
    schedule: "every day at 6:15am"
    
  scrape_company_s1_download:
    class: CompanyS1ScraperJob
    schedule: "every day at 6:30am"
    
  vectorize_s1_filings:
    class: VectorizeS1FilingsJob
    schedule: "every day at 6:40am"
    
  notify_subscribers:
    class: NotifySubscriberJob
    schedule: "every day at 7am"
